In [87]:
import numpy as np
import pandas as pd

In [88]:
movies=pd.read_csv('dataset/tmdb_5000_movies.csv')
credits=pd.read_csv('dataset/tmdb_5000_credits.csv')

In [89]:
movies.sample(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
4614,0,"[{""id"": 18, ""name"": ""Drama""}]",NaN,68412,"[{""id"": 10183, ""name"": ""independent film""}]",en,3 Backyards,The story of three people from the same suburb...,0.178170,"[{""name"": ""Caruso / Mendelsohn Productions"", ""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2010-01-01,0,88.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,3 Backyards,4.8,4
4650,0,"[{""id"": 53, ""name"": ""Thriller""}, {""id"": 9648, ...",http://www.examthemovie.com/,29917,"[{""id"": 1419, ""name"": ""gun""}, {""id"": 2834, ""na...",en,Exam,The final candidates for a highly desirable co...,20.265518,"[{""name"": ""Hazeldine Films"", ""id"": 5004}, {""na...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""}]",2009-06-19,0,101.0,"[{""iso_639_1"": ""cn"", ""name"": ""\u5e7f\u5dde\u8b...",Released,How far would you go to win the ultimate job?,Exam,6.6,523
2101,37000000,"[{""id"": 35, ""name"": ""Comedy""}]",NaN,12153,"[{""id"": 1568, ""name"": ""undercover""}, {""id"": 18...",en,White Chicks,"Two FBI agent brothers, Marcus and Kevin Copel...",28.703007,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2004-06-23,113086475,109.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,They're going deep undercover.,White Chicks,6.3,679

In [90]:
credits.sample(3)

,movie_id,title,cast,crew
2734,339984,Miracles from Heaven,"[{""cast_id"": 6, ""character"": ""Christy Beam"", ""...","[{""credit_id"": ""555286d3c3a3687f6300ac38"", ""de..."
2582,97367,The Place Beyond the Pines,"[{""cast_id"": 3, ""character"": ""Luke Glanton"", ""...","[{""credit_id"": ""52fe49dd9251416c750d5efb"", ""de..."
4481,2287,Rize,"[{""cast_id"": 2, ""character"": ""Himself"", ""credi...","[{""credit_id"": ""52fe434ac3a36847f8048ef3"", ""de..."

In [91]:
movies=movies.merge(credits,on='title')
movies.sample(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
3759,4000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 9648, ""n...",http://www.scoopmovie.net/,512,"[{""id"": 213, ""name"": ""upper class""}, {""id"": 54...",en,Scoop,An American journalism student in London scoop...,17.229537,"[{""name"": ""BBC Films"", ""id"": 288}, {""name"": ""I...",...,96.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The perfect man. The perfect story. The perfec...,Scoop,6.4,420,512,"[{""cast_id"": 4, ""character"": ""Sondra Pransky"",...","[{""credit_id"": ""52fe424cc3a36847f8013729"", ""de..."

In [92]:
movies=movies[['movie_id','title','overview','genres','keywords','cast','crew']]
movies.sample(2)

,movie_id,title,overview,genres,keywords,cast,crew
3828,3116,Midnight Cowboy,A naive male prostitute and his sickly friend ...,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 1879, ""name"": ""shower""}]","[{""cast_id"": 10, ""character"": ""'Ratso' Rizzo"",...","[{""credit_id"": ""52fe4388c3a36847f805b4fb"", ""de..."
2375,10549,Hamlet,"Hamlet, Prince of Denmark, returns home to fin...","[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 456, ""name"": ""mother""}, {""id"": 497, ""n...","[{""cast_id"": 1, ""character"": ""Prince Hamlet"", ...","[{""credit_id"": ""52fe43869251416c75013ba5"", ""de..."

In [93]:
movies.shape

(4809, 7)

### handling missing data and duplicate data

In [94]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [95]:
# since only 3 overview are missing and overview is very important feature in our dataset, dropping those rows
movies.dropna(subset=['overview'],inplace=True)

In [96]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [98]:
movies.duplicated().sum()

0

### Formatting textual columns

In [110]:
def format_column(list):
    formatted_list=[]
    for dict in list:
        for id,value in dict:
            formatted_list.append(value)
    return formatted_list

In [111]:
movies.genres.apply(format_column)

ValueError: not enough values to unpack (expected 2, got 1)